import {
  Briefcase,
  Cake,
  Coffee,
  Croissant,
  Heart,
  HeartHandshake,
  Martini,
  PartyPopper,
  LucideIcon,
} from "lucide-react";

export interface MenuDef {
  id: string;
  name: string;
  price: string;
  note?: string;
  items: string[];
}

export interface MenuCategory {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: LucideIcon;
  menus: MenuDef[];
}

export const menuCategories: MenuCategory[] = [
  {
    id: "business",
    title: "Business & Corporate Menus",
    shortTitle: "Business",
    description:
      "Business lunches, training days and breakfast meetings, delivered on time and set up ready to serve.",
    icon: Briefcase,
    menus: [
      {
        id: "light-lunch-1",
        name: "Light Lunch Menu 1",
        price: "£8.50 per head",
        items: [
          "Selection of sandwiches, brown & white bread, with a wide variety of fillings",
          "Variety of mini wraps",
          "Crisps & bites",
          "Vegetable spring rolls",
          "Chicken goujons served with sour cream & chive dip",
          "Cocktail sausage rolls",
          "Mini cake platter",
        ],
      },
      {
        id: "light-lunch-2",
        name: "Light Lunch Menu 2",
        price: "£8.75 per head",
        items: [
          "Selection of sandwiches, brown & white bread, with a wide variety of fillings",
          "Variety of mini wraps",
          "Vegetable samosa served with chutney",
          "Cheese pastries",
          "Crudités served with houmous dip",
          "Chicken goujons served with sour cream & chive dip",
          "Fresh fruit platter",
        ],
      },
      {
        id: "business-menu-b",
        name: "Business Menu B",
        price: "£8.95 per head",
        items: [
          "Chicken satay served with sour cream & chive dip",
          "Crudités served with houmous dip",
          "Selection of sandwiches with a wide variety of fillings, served on white, wholemeal & seeded bread",
          "Crisps, nachos & pringles served with a homemade salsa dip",
          "Vegetable spring rolls served with sweet chilli dip",
          "Cheese & grapes",
          "Fruit pots",
        ],
      },
      {
        id: "business-menu-c",
        name: "Business Menu C",
        price: "£9.75 per head",
        items: [
          "Chicken goujons served with sour cream & chive dip",
          "Crudités served with houmous dip",
          "Selection of sandwiches with a wide variety of fillings, served on white, wholemeal & seeded bread",
          "Crisps, nachos & pringles served with a homemade salsa dip",
          "Vegetable samosa",
          "Cocktail cheese pastries",
          "Spicy pakora served with chilli chutney",
          "Mixed vol au vents",
          "Vegetarian mini quiche selection",
          "Tiers of mini cakes",
        ],
      },
      {
        id: "business-menu-d",
        name: "Business Menu D",
        price: "£10.95 per head",
        items: [
          "Freshly baked bridge rolls, white & wholemeal, with a wide variety of fillings",
          "Spicy pakoras served with mint dip",
          "Mediterranean vegetable pizza slices",
          "Mini Melton Mowbray pork pies served with pickle",
          "Crudités served with homemade houmous dip",
          "Cumberland sausage rolls",
          "Mini quiche",
          "Chicken satay sticks",
          "Vegetable samosa",
          "Sections of homemade scotch eggs",
          "Bowls of hand-cooked crisps",
          "Homemade crunchy coleslaw",
          "Mini cakes",
        ],
      },
      {
        id: "menu-g",
        name: "Menu G",
        price: "£15.95 per head",
        note: "Minimum numbers apply. Please note this is a knife & fork buffet.",
        items: [
          "Mini filled sub rolls: red salmon & cucumber, mature cheddar & red onion, roast turkey & stuffing, roast beef, egg mayonnaise & cress",
          "Cream cheese & smoked salmon vol au vents",
          "Slices of homemade Spanish quiche",
          "Tandoori chicken drumsticks",
          "Crudités served with guacamole dip",
          "Lamb samosa",
          "Hand-cooked crisp selection",
          "Homemade crunchy coleslaw",
          "New potato salad",
          "Seafood platter",
          "Cheese & grapes",
          "Fresh fruit kebabs, small cakes",
        ],
      },
    ],
  },
  {
    id: "breakfast",
    title: "Breakfast Menu",
    shortTitle: "Breakfast",
    description:
      "Breakfast meetings and early starts — hot baps, pastries and fresh fruit, delivered and set up ready to serve.",
    icon: Croissant,
    menus: [
      {
        id: "breakfast-menu",
        name: "Breakfast Menu",
        price: "From £1.25",
        note: "Priced per item. Sourdough rolls available on request. Hot food is supplied in chafers and kept hot, on a help-yourself basis. Minimum numbers apply.",
        items: [
          "Bacon & sausage baps — £5.95",
          "Vegetarian sausage baps — £5.95",
          "Scrambled eggs, mushrooms & spinach — £5.95",
          "Pastries, croissants & muffins — £3.50 per head",
          "Large fresh fruit platter — £25.00",
          "Yoghurts with fruit & muesli — £1.25",
        ],
      },
    ],
  },
  {
    id: "parties",
    title: "Party Menus",
    shortTitle: "Parties",
    description:
      "Birthdays, anniversaries and celebrations of every kind — vibrant spreads that let you enjoy the party.",
    icon: PartyPopper,
    menus: [
      {
        id: "party-menu-h",
        name: "Party Menu H",
        price: "£7.95 per head",
        items: [
          "Selection of sandwiches on brown, white & seeded bread with a wide variety of fillings",
          "Chicken goujons served with sour cream & chive dip",
          "Cheese, grapes / pineapple",
          "Cumberland sausage rolls",
          "Wedges of pork pie",
          "Mini spring rolls served with sweet chilli dip",
          "Savoury eggs",
          "Vegetable samosa",
          "Crisps & bites served with homemade salsa dip",
          "Cocktail sausages",
          "Mini cakes",
        ],
      },
      {
        id: "party-menu-j",
        name: "Party Menu J",
        price: "£8.95 per head",
        items: [
          "Selection of sandwiches, brown & white, with a wide variety of fillings",
          "Sticky chicken sticks",
          "Cheese, grapes / pineapple",
          "Cumberland sausage rolls & cocktail cheese pastries",
          "Mini Melton Mowbray pork pies",
          "Mini pizza selection",
          "Sections of homemade scotch eggs",
          "Crisps & bites served with homemade salsa dip",
          "Cocktail sausage & bacon",
          "Mini vol au vents",
          "Vegetable samosa served with chutney",
          "Tiers of mini cakes",
        ],
      },
      {
        id: "party-menu-k",
        name: "Party Menu K",
        price: "£14.95 per head",
        items: [
          "Mini prawn cocktail pots / mini melon medley pots",
          "Selection of bridge rolls, brown & white, with a wide variety of fillings",
          "Sticky satay sticks served with sour cream & chive dip",
          "Cheese, grapes / pineapple",
          "Mini Melton Mowbray pork pies served with pickle & mustard",
          "Chicken tikka wraps / tuna savoury wraps",
          "Vegetable spring rolls served with sweet chilli dip",
          "Vegetable samosa served with chutney",
          "Crisps & bites served with homemade salsa dip",
          "Cocktail sausage & bacon",
          "Crudités with houmous dip",
          "Homemade coleslaw",
          "Pakora with chutney",
          "Mini cakes, trifles",
        ],
      },
      {
        id: "party-menu-l",
        name: "Party Menu L",
        price: "£15.95 per head",
        items: [
          "Mini filled sub rolls: red salmon & cucumber, mature cheddar & red onion, roast turkey & stuffing, roast beef, egg mayonnaise & cress",
          "Cream cheese & smoked salmon vol au vents",
          "Slices of homemade Spanish quiche",
          "Jerk chicken drumsticks",
          "Crudités served with guacamole dip",
          "Lamb samosa",
          "Hand-cooked crisp selection",
          "Homemade crunchy coleslaw",
          "New potato salad",
          "Seafood platter",
          "Cheese & grapes",
          "Fresh fruit kebabs",
          "Mini trifles",
          "Cheese board",
        ],
      },
    ],
  },
  {
    id: "wakes",
    title: "Wake Menus",
    shortTitle: "Wakes",
    description:
      "Respectful, reliable catering to help you honour a loved one, delivered with quiet professionalism.",
    icon: HeartHandshake,
    menus: [
      {
        id: "wake-menu-1",
        name: "Wake Menu 1",
        price: "£7.75 per head",
        items: [
          "Chicken goujons served with sour cream & chive dip",
          "Crudités served with houmous dip",
          "Selection of sandwiches with a wide variety of fillings, served on white, wholemeal & seeded bread",
          "Crisps, nachos & pringles served with a homemade salsa dip",
          "Mini vegetable spring rolls served with sweet chilli dip",
          "Mini quiche",
          "Cocktail sausage rolls",
          "Wedges of pork pie served with pickle",
          "Mini savoury eggs",
          "Cocktail sausage & bacon",
          "Mini cakes & traditional fruit cake",
        ],
      },
      {
        id: "wake-menu-2",
        name: "Wake Menu 2",
        price: "£8.75 per head",
        items: [
          "Seasoned roast chicken drumsticks",
          "Crudités served with houmous dip",
          "Selection of sandwiches with a wide variety of fillings, white & wholemeal bread",
          "Bowls of hand-cooked crisps",
          "Mini vegetable spring rolls served with sweet chilli dip",
          "Mini quiche selection",
          "Cocktail sausage rolls",
          "Mini Melton Mowbray pork pies served with pickle",
          "Cocktail sausage & bacon",
          "Homemade scotch eggs",
          "Tiers of mini cakes, traditional fruit cake",
        ],
      },
      {
        id: "wake-menu-3",
        name: "Wake Menu 3",
        price: "£4.95 per head",
        note: "Minimum numbers apply. Can be added to a cold buffet.",
        items: [
          "Hot roast pulled pork served in gravy",
          "With soft white baps",
          "Stuffing, apple sauce & mustard",
        ],
      },
    ],
  },
  {
    id: "christenings",
    title: "Christening Menus",
    shortTitle: "Christenings",
    description:
      "Warm, welcoming spreads for one of life's most treasured celebrations, suited to family and guests of all ages.",
    icon: Cake,
    menus: [
      {
        id: "christening-menu-a",
        name: "Christening Menu A",
        price: "£8.95 per head",
        items: [
          "Selection of sandwiches on brown, white & seeded bread",
          "Crisps & bites with salsa dip",
          "Sticky chicken sticks",
          "Cheese & grapes, cheese & pineapple",
          "Mini vegetable samosa",
          "Crudités served with dips",
          "Cumberland sausage rolls",
          "Sections of scotch eggs",
          "Mixed vol au vents",
          "Mini spring rolls with sweet chilli dip",
          "Tiers of mini cakes",
        ],
      },
      {
        id: "christening-menu-b",
        name: "Christening Menu B",
        price: "£9.95 per head",
        items: [
          "Mini sub rolls, brown & white, with a wide variety of fillings",
          "Crudités with houmous dip",
          "Vegetable samosa",
          "Cocktail sausage & bacon",
          "Chicken goujons served with sour cream & chive dip",
          "Cheese & onion pastries / sausage rolls",
          "Mini Melton Mowbray pork pies served with pickle & mustard",
          "Mini quiche",
          "Cheese, grapes / pineapple",
          "Trifles, tiers of cakes",
        ],
      },
      {
        id: "christening-menu-c",
        name: "Christening Menu C",
        price: "£12.95 per head",
        items: [
          "Selection of sandwiches on brown & white bread with a wide variety of fillings",
          "Tandoori-flavoured chicken drumsticks",
          "Cheese, grapes / pineapple",
          "Wedges of pork pie",
          "Cocktail pastries",
          "Vegetable spring rolls served with sweet chilli dip",
          "Hand-cooked crisps",
          "Mini quiche selection",
          "Coleslaw & potato salad",
          "Mini pizza",
          "Chicken samosa",
          "Smoked salmon & cream cheese vol au vents",
          "Chocolate fudge cake, trifle & cheesecake",
        ],
      },
    ],
  },
  {
    id: "canapes",
    title: "Canapé Menu",
    shortTitle: "Canapés",
    description:
      "Individually priced canapés for drinks receptions and welcome hours — mix and match to suit your event.",
    icon: Martini,
    menus: [
      {
        id: "canape-menu",
        name: "Canapé Selection",
        price: "£3.00 each",
        note: "Or any four canapés for £10.00.",
        items: [
          "Arancini balls",
          "Mushroom arancini balls",
          "Bruschetta",
          "Mango & chilli prawn skewers",
          "Smoked salmon & cream cheese curls",
          "Honey mustard sausages",
          "Tikka chicken skewers",
          "Mixed vol au vents",
          "Sticky chicken sticks",
          "Mini filled wraps",
          "Mini quiche",
          "Mozzarella pearls with cherry tomato",
          "Halloumi fingers",
          "Breadsticks & flatbread served with homemade red pepper houmous",
          "Curried chickpea cups",
          "Mini pastrami bagels",
          "Olive & chorizo skewers",
          "Stilton blinis",
          "Doughnut balls",
          "Chocolate fudge brownie",
          "Cheesecake squares",
          "Mini Victoria sponges",
          "Fruit kebabs",
          "Chocolate strawberries",
        ],
      },
    ],
  },
  {
    id: "refreshments",
    title: "Refreshments",
    shortTitle: "Refreshments",
    description:
      "Hot drinks, juices and pastries to add to any booking, priced individually.",
    icon: Coffee,
    menus: [
      {
        id: "refreshment-menu",
        name: "Refreshment Menu",
        price: "From £1.00",
        note: "Priced per item. Delivery of drinks only may incur a delivery charge.",
        items: [
          "Tea & coffee — £2.75 per head",
          "Flavoured teas — £2.50 per head",
          "Biscuits — £1.00 per head",
          "Morning pastries — £3.50 each",
          "Mini pastries — £1.75 each",
          "Orange juice — £4.00 per jug",
          "Apple juice — £4.00 per jug",
          "Sparkling elderflower — £4.50 per jug",
          "Individual water — £1.25 each",
        ],
      },
    ],
  },
  {
    id: "weddings",
    title: "Wedding Menus",
    shortTitle: "Weddings",
    description:
      "Buffets and platters for wedding receptions, from relaxed to formal.",
    icon: Heart,
    menus: [
      {
        id: "wedding-menu-1",
        name: "Wedding Menu 1",
        price: "£8.95 per head",
        items: [
          "Selection of sandwiches, brown & white, with a variety of fillings",
          "Tuna mayo & chicken tikka wraps",
          "Cheese & pineapple / grapes",
          "Cumberland sausage rolls / cheese pastries",
          "Mini quiche",
          "Cocktail sausage & bacon",
          "Crudités with homemade houmous dip",
          "Melton Mowbray pork pies served with pickle & mustard",
          "Samosas served with chutney & mint sauce",
          "Goujons served with sour cream & chive dip",
          "Crisps & bites with salsa dip",
          "Tiers of mini cakes, mini trifles",
        ],
      },
      {
        id: "wedding-menu-2",
        name: "Wedding Menu 2",
        price: "£9.75 per head",
        items: [
          "Selection of bridge rolls, brown & white bread, with a wide variety of fillings",
          "Mini wrap selection",
          "Mixed vol au vents",
          "Cheese, grapes / pineapple",
          "Cocktail sausage rolls / cheese pastries",
          "Crisps & savoury bites served with salsa dip",
          "Vegetable spring rolls served with sweet chilli dip",
          "Chicken satay sticks",
          "Onion bhajis served with mango chutney",
          "Crudités served with houmous",
          "Mini cake selection, mini trifles",
        ],
      },
      {
        id: "wedding-menu-3",
        name: "Wedding Menu 3",
        price: "£14.95 per head",
        items: [
          "Mini prawn cocktail pots / mini melon medley pots",
          "Selection of bridge rolls, brown & white, with a wide variety of fillings",
          "Sticky satay sticks served with sour cream & chive dip",
          "Cheese, grapes / pineapple",
          "Mini Melton Mowbray pork pies served with pickle",
          "Chicken tikka wraps / tuna savoury wraps",
          "Vegetable spring rolls served with sweet chilli dip",
          "Mozzarella sticks",
          "Chicken & meat samosa served with chutney",
          "Cocktail sausages",
          "Crudités with houmous dip",
          "Homemade coleslaw & pasta salad dish",
          "Tiers of mini cakes inc. trifles",
          "Gateaux, cheesecake",
        ],
      },
      {
        id: "wedding-menu-4",
        name: "Wedding Menu 4",
        price: "£18.00 per head",
        items: [
          "Mini filled sub rolls: red salmon & cucumber, mature cheddar & red onion, roast turkey & stuffing, roast beef, egg mayonnaise & cress",
          "Cream cheese & smoked salmon vol au vents, pâté vol au vents",
          "Seasoned chicken drumsticks",
          "Crudités served with guacamole",
          "Meat samosa served with chutney",
          "Hand-cooked crisp selection",
          "Homemade crunchy coleslaw",
          "New potato salad",
          "Seafood platter",
          "Charcuterie meat platter",
          "Breads with dipping oils",
          "Cheese board with grapes & celery",
          "Fresh fruit kebabs, deep-filled chocolate fudge cake, New York cheesecake",
        ],
      },
    ],
  },
];
